### ISSUE TITLE
Module not found: Error: Can't resolve './factoryWithThrowingShims' in 'C:\Myproject\prop-types'

### ISSUE THREAD

**Issue by mindingdata** [jacobbuck/react-shielded#11]
I recently asked a question on Stackoverflow that is related to this project : https://stackoverflow.com/questions/76266671/module-not-found-error-cant-resolve-factorywiththrowingshims-in-c-mypro

I added react-shielded to an existing project, and my build no longer works. It's more an issue with various libraries dependencies on prop-types (Including this one deep down), but any hints on how to resolve would be very much appreciated. 

Adding this library makes this change in my lock file : 

![image](https://github.com/jacobbuck/react-shielded/assets/1021021/998fbe90-e42f-40aa-b54c-f299a78a4a64)

Which seems to send things into chaos. 

I believe it could also be related to this : https://github.com/alibaba/BizCharts/issues/99. Where prop-types should be marked as external in your build. 

Not exactly a pro when it comes to packaging libraries, but it's possible that in your rollup you need to mark prop-types as external https://github.com/jacobbuck/react-shielded/blob/main/rollup.config.mjs. 

I think the drag of the prop-types is from your other project here : https://github.com/jacobbuck/react-document-portal (Which however does mark the prop types as external : https://github.com/jacobbuck/react-document-portal/blob/main/rollup.config.js, so I'm not really too sure :\ )

**Comment by aliebuck** [comment]
The issue seems to be with your bundler. I haven't come across this in any of my projects using this, so I'm not sure how to help sorry.
