### ISSUE TITLE
Two close button shows up in the modal

### ISSUE THREAD

**Issue by JieHuangStuff** [jacobbuck/react-shielded#9]
Sandbox: https://codesandbox.io/s/misty-architecture-ku6tqd?file=/src/App.js
Screenshot:
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/122754426/227821901-0aa48bdc-a1e7-4899-8ad6-91fae1abb029.png">

Seems like https://staticcdn.co.nz/ provided a CLOSE button recently
<img width="268" alt="image" src="https://user-images.githubusercontent.com/122754426/227822194-814dc5ea-4ec9-430c-878d-339b2d7d75dc.png">

**Comment by aliebuck** [comment]
Looks like there were some changes made last month: https://shielded.co.nz/#changesToWidget

I'll update this library to accomodate

**Comment by aliebuck** [comment]
Fixed in v2.1.0 😄
